@startuml
skinparam DPI 200
title Emergency Stop Timing, Watchdog Timeout

robust "Contactor" as Contactor
Contactor has 24V,0V
robust "Controlled Stop" as ControlledStop
ControlledStop has 24V,0V
robust "Zero Speed" as ZeroSpeed
ZeroSpeed has 24V,0V
robust "Emergency Stop" as EmergencyStop
EmergencyStop has 24V,0V
concise "Watchdog" as Watchdog
analog "Motor Speed" as MotorSpeed
robust "AC Supply" as Line
Line has Live,Dead

@0
Line is Live
Contactor is 24V
ControlledStop is 24V
ZeroSpeed is 0V
EmergencyStop is 24V
Watchdog is Idle
MotorSpeed is 100

@1
EmergencyStop is 0V

@2
ControlledStop is 0V
Watchdog is Alert

@3
MotorSpeed is 100

@4
Watchdog is Panicked
Watchdog -> MotorSpeed : Expects Zero
Watchdog -> ZeroSpeed : Expects Zero
Contactor is 0V



@5
MotorSpeed is 15
Line is Dead

@6
MotorSpeed is 0

EmergencyStop@1 <-> @2 : Debounced
MotorSpeed@2 <-> @3 : Response Time
Contactor@4 <-> @5 : Contactor Response Time

highlight 3 to 5 #seashell : Controlled Stop
highlight 5 to 6 #peachpuff : Un-controlled Stop

@enduml

